Lab 4
marcusregann/cmpt221 pull request #4
Opened 2024-09-30 21:02 UTC by marcusregann

2024-10-03 02:22 UTC, profphip requested changes
Hey there! Don't forget to add the double quotes to the table names. Just make that change and I can give you full credit!

2024-10-03 16:45 UTC, marcusregann commented
Hello Professor Calista! I believe I have added the double quotes to the table names. Please let me know if this is done right when you get the chance. Thank you.

2024-10-12 02:56 UTC, profphip approved these changes

2024-10-12 02:56 UTC, profphip commented
Looks good! I'm going to approve this and give you full credit because I forgot to mention you also need double quotes around column names. Don't forget those moving forward!

2024-10-16 00:44 UTC, merged